import { test, expect, type Page } from '@playwright/test';

const snapshot = (page: Page) => page.evaluate(() => (window as any).__dough.snapshot());
test('desktop: ground clicks do not move; keyboard movement and saved harvest work', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Let’s make pizza', exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/desktop-intro.png' });
  await page.getByRole('button', { name: 'Let’s make pizza', exact: true }).click();
  await expect(page.locator('.hud')).toBeVisible();
  await page.waitForTimeout(1200);
  const initial = await snapshot(page);
  await page.keyboard.down('d'); await page.waitForTimeout(350); await page.keyboard.up('d');
  expect((await snapshot(page)).position.x).toBeGreaterThan(initial.position.x);
  const beforeArrow = await snapshot(page);
  await page.keyboard.down('ArrowUp'); await page.waitForTimeout(350); await page.keyboard.up('ArrowUp');
  expect((await snapshot(page)).position.z).toBeLessThan(beforeArrow.position.z);
  const beforeClick = await snapshot(page);
  const screen = await page.evaluate(() => (window as any).__dough.project({ x: -6, z: -2 }));
  await page.mouse.click(screen.x, screen.y);
  await page.waitForTimeout(600);
  expect((await snapshot(page)).position).toEqual(beforeClick.position);
  await page.keyboard.down('w'); await page.waitForTimeout(1800); await page.keyboard.up('w');
  await expect.poll(async () => (await snapshot(page)).grain).toBeGreaterThan(0);
  await page.screenshot({ path: 'test-results/desktop-harvest.png' });
  const savedGrain = (await snapshot(page)).grain;
  await page.getByRole('button', { name: /Little upgrades/ }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Buy A bigger basket for 36 coins' })).toBeDisabled();
  await page.screenshot({ path: 'test-results/desktop-upgrades.png' });
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.keyboard.press('Escape');
  const paused = await snapshot(page);
  await page.waitForTimeout(500);
  expect((await snapshot(page)).elapsed).toBe(paused.elapsed);
  await page.getByRole('button', { name: 'Keep cooking' }).click();
  await page.reload();
  await page.getByRole('button', { name: 'Back to the farm' }).click();
  expect((await snapshot(page)).grain).toBe(savedGrain);
  await page.waitForTimeout(1000);
  await page.screenshot({ path: 'test-results/desktop-game.png' });
  console.log('Desktop render stats:', await page.evaluate(() => (window as any).__dough.renderInfo()));
  expect(errors).toEqual([]);
});

test('phone: layout, touch joystick, pause, and shop controls', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
  const page = await context.newPage();
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto('/');
  await page.waitForTimeout(1000);
  await page.screenshot({ path: 'test-results/phone-intro.png' });
  await page.getByRole('button', { name: 'Let’s make pizza', exact: true }).tap();
  await expect(page.locator('#joystick')).toBeVisible();
  await page.waitForTimeout(1500);
  const before = await snapshot(page);
  const joystick = await page.locator('#joystick').boundingBox();
  const cdp = await context.newCDPSession(page);
  const x = joystick!.x + joystick!.width / 2, y = joystick!.y + joystick!.height / 2;
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y, id: 1 }] });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x - 8, y: y - 35, id: 1 }] });
  await page.waitForTimeout(1600);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  const after = await snapshot(page);
  expect(Math.hypot(before.position.x - after.position.x, before.position.z - after.position.z)).toBeGreaterThan(2);
  expect(after.grain).toBeGreaterThan(0);
  await page.screenshot({ path: 'test-results/phone-game.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y, id: 1 }] });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x + 5, y: y - 35, id: 1 }] });
  await expect.poll(async () => (await snapshot(page)).grain).toBe(18);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await expect(page.locator('#edge-guide')).toBeVisible();
  await expect(page.locator('#edge-guide-name')).toHaveText('Kitchen');
  await page.screenshot({ path: 'test-results/phone-directions.png' });
  const beforeTap = await snapshot(page);
  const marker = await page.locator('#edge-guide').boundingBox();
  await page.touchscreen.tap(marker!.x + marker!.width / 2, marker!.y + marker!.height / 2);
  await page.waitForTimeout(600);
  expect((await snapshot(page)).position).toEqual(beforeTap.position);
  await page.getByRole('button', { name: /Little upgrades/ }).tap();
  await expect(page.getByRole('heading', { name: 'Little upgrades' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Buy A bigger basket for 36 coins' })).toBeDisabled();
  await page.screenshot({ path: 'test-results/phone-upgrades.png' });
  await page.getByRole('button', { name: 'Close', exact: true }).tap();
  await page.getByRole('button', { name: 'Pause game', exact: true }).tap();
  await expect(page.getByRole('heading', { name: 'Taking a little break' })).toBeVisible();
  expect(errors).toEqual([]);
  await context.close();
});
