import { test, expect, type Page } from '@playwright/test';

const snapshot = (page: Page) => page.evaluate(() => (window as any).__dough.snapshot());
async function walkTo(page: Page, target: { x: number; z: number }) {
  const screen = await page.evaluate(target => (window as any).__dough.project(target), target);
  await page.mouse.click(screen.x, screen.y);
  await expect.poll(async () => {
    const { position } = await snapshot(page);
    return Math.hypot(position.x - target.x, position.z - target.z);
  }, { timeout: 20_000 }).toBeLessThan(.7);
}

test('desktop: play the complete loop, upgrade, pause, and reload saved progress', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Let’s make pizza', exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/desktop-intro.png' });
  await page.getByRole('button', { name: 'Let’s make pizza', exact: true }).click();
  await expect(page.locator('.hud')).toBeVisible();
  await page.waitForTimeout(1200);
  const initial = await snapshot(page);
  await page.keyboard.down('d'); await page.waitForTimeout(350); await page.keyboard.up('d');
  expect((await snapshot(page)).position.x).toBeGreaterThan(initial.position.x);

  await walkTo(page, { x: -6, z: -2 });
  await walkTo(page, { x: -8, z: -4 });
  await expect.poll(async () => (await snapshot(page)).grain).toBe(18);
  await page.screenshot({ path: 'test-results/desktop-harvest.png' });
  await walkTo(page, { x: .3, z: -3.2 });
  await expect.poll(async () => (await snapshot(page)).grain).toBe(0);
  await expect.poll(async () => (await snapshot(page)).readyPizzas).toBeGreaterThan(0);
  await walkTo(page, { x: 5.1, z: -1.4 });
  await expect.poll(async () => (await snapshot(page)).pizzas, { timeout: 25_000 }).toBe(6);
  await walkTo(page, { x: 7.3, z: 4.2 });
  await expect.poll(async () => (await snapshot(page)).served).toBe(6);
  expect((await snapshot(page)).coins).toBe(72);
  await page.getByRole('button', { name: /Little upgrades/ }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByRole('button', { name: 'Buy A bigger basket for 36 coins' }).click();
  expect((await snapshot(page)).capacity).toBe(27);
  expect((await snapshot(page)).coins).toBe(36);
  await expect(page.getByRole('button', { name: 'Buy A hotter oven for 48 coins' })).toBeDisabled();
  await page.screenshot({ path: 'test-results/desktop-upgrades.png' });
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.keyboard.press('Escape');
  const paused = await snapshot(page);
  await page.waitForTimeout(500);
  expect((await snapshot(page)).elapsed).toBe(paused.elapsed);
  await page.getByRole('button', { name: 'Keep cooking' }).click();
  await page.reload();
  await page.getByRole('button', { name: 'Back to the farm' }).click();
  expect((await snapshot(page)).served).toBe(6);
  expect((await snapshot(page)).coins).toBe(36);
  expect((await snapshot(page)).capacity).toBe(27);
  await page.waitForTimeout(1000);
  await page.screenshot({ path: 'test-results/desktop-game.png' });
  console.log('Desktop render stats:', await page.evaluate(() => (window as any).__dough.renderInfo()));
  expect(errors).toEqual([]);
});

test('phone: layout, touch joystick, pause, and shop controls', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
  const page = await context.newPage();
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto('/');
  await page.waitForTimeout(1000);
  await page.screenshot({ path: 'test-results/phone-intro.png' });
  await page.getByRole('button', { name: 'Let’s make pizza', exact: true }).tap();
  await expect(page.locator('#joystick')).toBeVisible();
  await page.waitForTimeout(1500);
  const before = await snapshot(page);
  const joystick = await page.locator('#joystick').boundingBox();
  const cdp = await context.newCDPSession(page);
  const x = joystick!.x + joystick!.width / 2, y = joystick!.y + joystick!.height / 2;
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y, id: 1 }] });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x - 8, y: y - 35, id: 1 }] });
  await page.waitForTimeout(1600);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  const after = await snapshot(page);
  expect(Math.hypot(before.position.x - after.position.x, before.position.z - after.position.z)).toBeGreaterThan(2);
  expect(after.grain).toBeGreaterThan(0);
  await page.screenshot({ path: 'test-results/phone-game.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y, id: 1 }] });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x + 5, y: y - 35, id: 1 }] });
  await expect.poll(async () => (await snapshot(page)).grain).toBe(18);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await expect(page.getByRole('button', { name: 'Walk to kitchen' })).toBeVisible();
  await page.screenshot({ path: 'test-results/phone-directions.png' });
  await page.getByRole('button', { name: 'Walk to kitchen' }).tap();
  await expect.poll(async () => (await snapshot(page)).grain, { timeout: 20_000 }).toBe(0);
  await page.getByRole('button', { name: /Little upgrades/ }).tap();
  await expect(page.getByRole('heading', { name: 'Little upgrades' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Buy A bigger basket for 36 coins' })).toBeDisabled();
  await page.screenshot({ path: 'test-results/phone-upgrades.png' });
  await page.getByRole('button', { name: 'Close', exact: true }).tap();
  await page.getByRole('button', { name: 'Pause game', exact: true }).tap();
  await expect(page.getByRole('heading', { name: 'Taking a little break' })).toBeVisible();
  expect(errors).toEqual([]);
  await context.close();
});
